// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MemberDetailEventsStatus.
const (
	Completed MemberDetailEventsStatus = "completed"
	Upcoming  MemberDetailEventsStatus = "upcoming"
)

// BasicInfo defines model for BasicInfo.
type BasicInfo struct {
	Faculty   string `json:"faculty"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Nickname  string `json:"nickname"`

	// SelfIntroduction Markdown形式の自己紹介文
	SelfIntroduction string     `json:"self_introduction"`
	StudentId        string     `json:"student_id"`
	Visibility       Visibility `json:"visibility"`
}

// LineOAuthResponse defines model for LineOAuthResponse.
type LineOAuthResponse struct {
	// AccessToken LINEから発行されたアクセストークン
	AccessToken string `json:"access_token"`

	// ExpiresIn アクセストークンの有効期限(秒)
	ExpiresIn int `json:"expires_in"`

	// RefreshToken 必要に応じて返されるリフレッシュトークン
	RefreshToken *string  `json:"refresh_token,omitempty"`
	User         LineUser `json:"user"`
}

// LineUser defines model for LineUser.
type LineUser struct {
	// DisplayName 表示名
	DisplayName string `json:"display_name"`

	// PictureUrl プロフィール画像URL
	PictureUrl *string `json:"picture_url,omitempty"`

	// StatusMessage ステータスメッセージ
	StatusMessage *string `json:"status_message,omitempty"`

	// UserId LINEユーザーID
	UserId string `json:"user_id"`
}

// MemberDetail defines model for MemberDetail.
type MemberDetail struct {
	Accounts struct {
		Discord bool `json:"discord"`
		Github  bool `json:"github"`
		Line    bool `json:"line"`
	} `json:"accounts"`
	Avatar *string `json:"avatar,omitempty"`

	// Bio Markdown形式の自己紹介
	Bio        string `json:"bio"`
	Department string `json:"department"`
	Events     []struct {
		Date   openapi_types.Date       `json:"date"`
		Name   string                   `json:"name"`
		Status MemberDetailEventsStatus `json:"status"`
	} `json:"events"`
	Id    string `json:"id"`
	Links []struct {
		Title string `json:"title"`
		Url   string `json:"url"`
	} `json:"links"`
	Name     string   `json:"name"`
	Nickname string   `json:"nickname"`
	Roles    []string `json:"roles"`
	Year     string   `json:"year"`
}

// MemberDetailEventsStatus defines model for MemberDetail.Events.Status.
type MemberDetailEventsStatus string

// MemberSummary defines model for MemberSummary.
type MemberSummary struct {
	Avatar   *string  `json:"avatar,omitempty"`
	Id       string   `json:"id"`
	Name     string   `json:"name"`
	Nickname string   `json:"nickname"`
	Roles    []string `json:"roles"`
}

// UpdateResponse defines model for UpdateResponse.
type UpdateResponse struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// Visibility defines model for Visibility.
type Visibility struct {
	Instagram        bool `json:"instagram"`
	Name             bool `json:"name"`
	SelfIntroduction bool `json:"self_introduction"`
	X                bool `json:"x"`
}

// GetApiLineOauthParams defines parameters for GetApiLineOauth.
type GetApiLineOauthParams struct {
	// Code LINE OAuth認可コード
	Code string `form:"code" json:"code"`

	// State CSRF対策のstate値
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// PutApiProfileBasicInfoJSONRequestBody defines body for PutApiProfileBasicInfo for application/json ContentType.
type PutApiProfileBasicInfoJSONRequestBody = BasicInfo

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LINE OAuthコールバック
	// (GET /api/line-oauth)
	GetApiLineOauth(c *gin.Context, params GetApiLineOauthParams)
	// メンバー一覧を取得する
	// (GET /api/members)
	GetApiMembers(c *gin.Context)
	// メンバー詳細を取得する
	// (GET /api/members/{id})
	GetApiMembersId(c *gin.Context, id string)
	// 基本情報を取得する
	// (GET /api/profile/basic-info)
	GetApiProfileBasicInfo(c *gin.Context)
	// 基本情報を更新する
	// (PUT /api/profile/basic-info)
	PutApiProfileBasicInfo(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiLineOauth operation middleware
func (siw *ServerInterfaceWrapper) GetApiLineOauth(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiLineOauthParams

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiLineOauth(c, params)
}

// GetApiMembers operation middleware
func (siw *ServerInterfaceWrapper) GetApiMembers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiMembers(c)
}

// GetApiMembersId operation middleware
func (siw *ServerInterfaceWrapper) GetApiMembersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiMembersId(c, id)
}

// GetApiProfileBasicInfo operation middleware
func (siw *ServerInterfaceWrapper) GetApiProfileBasicInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiProfileBasicInfo(c)
}

// PutApiProfileBasicInfo operation middleware
func (siw *ServerInterfaceWrapper) PutApiProfileBasicInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiProfileBasicInfo(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/line-oauth", wrapper.GetApiLineOauth)
	router.GET(options.BaseURL+"/api/members", wrapper.GetApiMembers)
	router.GET(options.BaseURL+"/api/members/:id", wrapper.GetApiMembersId)
	router.GET(options.BaseURL+"/api/profile/basic-info", wrapper.GetApiProfileBasicInfo)
	router.PUT(options.BaseURL+"/api/profile/basic-info", wrapper.PutApiProfileBasicInfo)
}
