openapi: 3.1.0
info:
  title: 基本情報編集API
  version: 1.0.0
  description: ユーザーの基本情報を編集するためのAPI
paths:
  /api/profile/basic-info:
    put:
      summary: 基本情報を更新する
      description: 学籍番号や名前、自己紹介などの基本情報を編集します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - student_id
                - faculty
                - last_name
                - first_name
                - nickname
                - self_introduction
                - visibility
              properties:
                student_id:
                  type: string
                  example: B1234567
                faculty:
                  type: string
                  example: 情報工学部
                last_name:
                  type: string
                  example: 田中
                first_name:
                  type: string
                  example: 太郎
                nickname:
                  type: string
                  example: たなたろ
                self_introduction:
                  type: string
                  description: Markdown形式の自己紹介文
                  example: |
                    # 自己紹介
                    
                    プログラミングが好きな2年生です！
                    
                    ## 興味のある分野
                    - **Webアプリ開発**
                    - **機械学習**
                visibility:
                  type: object
                  properties:
                    name:
                      type: boolean
                      example: false
                    self_introduction:
                      type: boolean
                      example: true
                    x:
                      type: boolean
                      example: false
                    instagram:
                      type: boolean
                      example: true
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 基本情報を更新しました。
        '400':
          description: バリデーションエラー
        '500':
          description: サーバーエラー

