/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BasicInfo } from '../models';
// @ts-ignore
import type { LineOAuthResponse } from '../models';
// @ts-ignore
import type { MemberDetail } from '../models';
// @ts-ignore
import type { MemberSummary } from '../models';
// @ts-ignore
import type { UpdateResponse } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * LINEのOAuthコールバックURLとして、付与されたcodeをアクセストークンに交換し、認証済みユーザー情報を返します。
         * @summary LINE OAuthコールバック
         * @param {string} code LINE OAuth認可コード
         * @param {string} [state] CSRF対策のstate値
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLineOauthGet: async (code: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('apiLineOauthGet', 'code', code)
            const localVarPath = `/api/line-oauth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * サークルメンバーのサマリ情報一覧を返します。
         * @summary メンバー一覧を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMembersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/members`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 指定したメンバーの詳細情報を返します。
         * @summary メンバー詳細を取得する
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMembersIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiMembersIdGet', 'id', id)
            const localVarPath = `/api/members/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 現在登録されているユーザーの基本情報を返します。
         * @summary 基本情報を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/profile/basic-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 学籍番号や名前、自己紹介などの基本情報を編集します。
         * @summary 基本情報を更新する
         * @param {BasicInfo} basicInfo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoPut: async (basicInfo: BasicInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'basicInfo' is not null or undefined
            assertParamExists('apiProfileBasicInfoPut', 'basicInfo', basicInfo)
            const localVarPath = `/api/profile/basic-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(basicInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * LINEのOAuthコールバックURLとして、付与されたcodeをアクセストークンに交換し、認証済みユーザー情報を返します。
         * @summary LINE OAuthコールバック
         * @param {string} code LINE OAuth認可コード
         * @param {string} [state] CSRF対策のstate値
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLineOauthGet(code: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LineOAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiLineOauthGet(code, state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiLineOauthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * サークルメンバーのサマリ情報一覧を返します。
         * @summary メンバー一覧を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMembersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MemberSummary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiMembersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiMembersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 指定したメンバーの詳細情報を返します。
         * @summary メンバー詳細を取得する
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMembersIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MemberDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiMembersIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiMembersIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 現在登録されているユーザーの基本情報を返します。
         * @summary 基本情報を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProfileBasicInfoGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BasicInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiProfileBasicInfoGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiProfileBasicInfoGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 学籍番号や名前、自己紹介などの基本情報を編集します。
         * @summary 基本情報を更新する
         * @param {BasicInfo} basicInfo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProfileBasicInfoPut(basicInfo: BasicInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiProfileBasicInfoPut(basicInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiProfileBasicInfoPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * LINEのOAuthコールバックURLとして、付与されたcodeをアクセストークンに交換し、認証済みユーザー情報を返します。
         * @summary LINE OAuthコールバック
         * @param {string} code LINE OAuth認可コード
         * @param {string} [state] CSRF対策のstate値
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLineOauthGet(code: string, state?: string, options?: RawAxiosRequestConfig): AxiosPromise<LineOAuthResponse> {
            return localVarFp.apiLineOauthGet(code, state, options).then((request) => request(axios, basePath));
        },
        /**
         * サークルメンバーのサマリ情報一覧を返します。
         * @summary メンバー一覧を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMembersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<MemberSummary>> {
            return localVarFp.apiMembersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 指定したメンバーの詳細情報を返します。
         * @summary メンバー詳細を取得する
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMembersIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<MemberDetail> {
            return localVarFp.apiMembersIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 現在登録されているユーザーの基本情報を返します。
         * @summary 基本情報を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoGet(options?: RawAxiosRequestConfig): AxiosPromise<BasicInfo> {
            return localVarFp.apiProfileBasicInfoGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 学籍番号や名前、自己紹介などの基本情報を編集します。
         * @summary 基本情報を更新する
         * @param {BasicInfo} basicInfo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoPut(basicInfo: BasicInfo, options?: RawAxiosRequestConfig): AxiosPromise<UpdateResponse> {
            return localVarFp.apiProfileBasicInfoPut(basicInfo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * LINEのOAuthコールバックURLとして、付与されたcodeをアクセストークンに交換し、認証済みユーザー情報を返します。
     * @summary LINE OAuthコールバック
     * @param {string} code LINE OAuth認可コード
     * @param {string} [state] CSRF対策のstate値
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiLineOauthGet(code: string, state?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiLineOauthGet(code, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * サークルメンバーのサマリ情報一覧を返します。
     * @summary メンバー一覧を取得する
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiMembersGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiMembersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 指定したメンバーの詳細情報を返します。
     * @summary メンバー詳細を取得する
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiMembersIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiMembersIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 現在登録されているユーザーの基本情報を返します。
     * @summary 基本情報を取得する
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiProfileBasicInfoGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiProfileBasicInfoGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 学籍番号や名前、自己紹介などの基本情報を編集します。
     * @summary 基本情報を更新する
     * @param {BasicInfo} basicInfo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiProfileBasicInfoPut(basicInfo: BasicInfo, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiProfileBasicInfoPut(basicInfo, options).then((request) => request(this.axios, this.basePath));
    }
}

