/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LineUser } from './line-user';

/**
 * 
 * @export
 * @interface LineOAuthResponse
 */
export interface LineOAuthResponse {
    /**
     * LINEから発行されたアクセストークン
     * @type {string}
     * @memberof LineOAuthResponse
     */
    'access_token': string;
    /**
     * 必要に応じて返されるリフレッシュトークン
     * @type {string}
     * @memberof LineOAuthResponse
     */
    'refresh_token'?: string;
    /**
     * アクセストークンの有効期限(秒)
     * @type {number}
     * @memberof LineOAuthResponse
     */
    'expires_in': number;
    /**
     * 
     * @type {LineUser}
     * @memberof LineOAuthResponse
     */
    'user': LineUser;
}

