/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LineUser
 */
export interface LineUser {
    /**
     * LINEユーザーID
     * @type {string}
     * @memberof LineUser
     */
    'user_id': string;
    /**
     * 表示名
     * @type {string}
     * @memberof LineUser
     */
    'display_name': string;
    /**
     * プロフィール画像URL
     * @type {string}
     * @memberof LineUser
     */
    'picture_url'?: string;
    /**
     * ステータスメッセージ
     * @type {string}
     * @memberof LineUser
     */
    'status_message'?: string;
}

