/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemberCreateResponse
 */
export interface MemberCreateResponse {
    /**
     * 登録されたメンバーのID
     * @type {string}
     * @memberof MemberCreateResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MemberCreateResponse
     */
    'message': string;
}

