/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemberSummary
 */
export interface MemberSummary {
    /**
     * 
     * @type {string}
     * @memberof MemberSummary
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MemberSummary
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof MemberSummary
     */
    'nickname': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberSummary
     */
    'roles': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MemberSummary
     */
    'avatar'?: string;
}

