/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemberDetailAllOfAccounts } from './member-detail-all-of-accounts';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberDetailAllOfEvents } from './member-detail-all-of-events';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberDetailAllOfLinks } from './member-detail-all-of-links';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberSummary } from './member-summary';

/**
 * @type MemberDetail
 * @export
 */
export type MemberDetail = MemberSummary;


