/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemberDetailAllOfEvents
 */
export interface MemberDetailAllOfEvents {
    /**
     * 
     * @type {string}
     * @memberof MemberDetailAllOfEvents
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof MemberDetailAllOfEvents
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof MemberDetailAllOfEvents
     */
    'status': MemberDetailAllOfEventsStatusEnum;
}

export const MemberDetailAllOfEventsStatusEnum = {
    Upcoming: 'upcoming',
    Completed: 'completed'
} as const;

export type MemberDetailAllOfEventsStatusEnum = typeof MemberDetailAllOfEventsStatusEnum[keyof typeof MemberDetailAllOfEventsStatusEnum];


