/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemberCreateAccounts
 */
export interface MemberCreateAccounts {
    /**
     * 
     * @type {boolean}
     * @memberof MemberCreateAccounts
     */
    'line': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberCreateAccounts
     */
    'discord': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberCreateAccounts
     */
    'github': boolean;
}

