/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemberCreateAccounts } from './member-create-accounts';
// May contain unused imports in some cases
// @ts-ignore
import type { MemberDetailAllOfLinks } from './member-detail-all-of-links';

/**
 * 
 * @export
 * @interface MemberCreate
 */
export interface MemberCreate {
    /**
     * 
     * @type {string}
     * @memberof MemberCreate
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof MemberCreate
     */
    'nickname': string;
    /**
     * 
     * @type {string}
     * @memberof MemberCreate
     */
    'department': string;
    /**
     * 
     * @type {string}
     * @memberof MemberCreate
     */
    'year': string;
    /**
     * Markdown形式の自己紹介
     * @type {string}
     * @memberof MemberCreate
     */
    'bio': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberCreate
     */
    'roles': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MemberCreate
     */
    'avatar'?: string;
    /**
     * 
     * @type {MemberCreateAccounts}
     * @memberof MemberCreate
     */
    'accounts': MemberCreateAccounts;
    /**
     * 
     * @type {Array<MemberDetailAllOfLinks>}
     * @memberof MemberCreate
     */
    'links'?: Array<MemberDetailAllOfLinks>;
}

